### ISSUE TITLE
Add gas costs

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuel-specs#10]
Opcodes currently don't have gas costs. These need to be specified.

**Comment by Voxelot** [comment]
@adlerjohn this could likely be closed, as we now have a gas schedule benchmarking framework that we are iterating on.

**Comment by otrho** [comment]
Don't we want them properly documented somewhere?  If I wanted to know individual op costs (which I do when writing optimisers) where should I look?

**Comment by Voxelot** [comment]
We are working on a framework to autogenerate a yaml file of the costs based on bechmarks, and also generate a [rust file](https://github.com/FuelLabs/fuel-vm/blob/9575546b8ed6cbd145a553cef37dd484a8915b7d/src/gas/default_gas_costs.rs) which contains the instantiated gas costs.

As we expect the gas costs to change over time as we add more functionality like merkle trees or optimize the vm/client, I'm not sure if statically binding them to the specs is the best move right now.
