### ISSUE TITLE
Support withdrawal of resources minted on Fuel

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/fuel-specs#112]
## Motivation:
We would ideally like contracts to be able to create new UTXO colors (token IDs) within a Fuel contract without having to deploy the contract on Ethereum L1, while also having some pathway for Ethereum contract creation, in the event someone wants to withdraw these tokens.

## Proposal
Ideally, even if a contract has not been created yet on Ethereum for the color, a contract can specify/mint a new UTXO type (akin to Move resources) such that contracts can now create UTXOs in addition to just intaking and outputting them.

In addition to this, a 32 byte contract bytecode hash should be specified and registered in state, in the event someone wants to withdraw these this new token color, the user would be required to create the exact contract specified in the preimage of the bytecode hash before withdrawing (simple logic that can be added to the withdraw function).

This way, in the event of a withdraw, a contract can be created on Ethereum to exact specification, and then the withdraw can occur.

## Status
This idea is at the early stages, still considering all the UTXO edge cases.

**Comment by adlerjohn** [comment]
Superseded by #317
