### ISSUE TITLE
Domain separate predicate hash, address and blocks

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuel-specs#201]
Currently, the predicate hash and address (pubkey hash) aren't domain separated. This means if a pubkey happens to have a predicate bytecode that can evaluate to `true` with some easy-to-find parameters, then anyone can spend the UTXO. Getting the predicate hash and the address should therefore be domain-separated.

**Comment by Voxelot** [comment]
Now that UtxoId's are based on transaction and output index, the above domain separated hash scheme may need some changes.

**Comment by MitchTurner** [comment]
Is this something we want before mainnet? @xgreenx @Voxelot 
If not, we can remove from Fuel Project Board.

**Comment by Voxelot** [comment]
Correct @xgreenx, this particular issue was solved when I started down the path of including [chain id's](https://github.com/FuelLabs/fuel-specs/pull/462) into the predicate id. Even though we decided not to use chain ids there anymore, it still uses domain separation based on the contract id domain separator:
> `0x4655454C`
