### ISSUE TITLE
Fully specify p2sh verification of predicates

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-specs#264]
The specs reference p2sh when discussing predicate verification, but the exact requirements for this aren't currently clear. We should update the predicate validation specs to include a section about how the hash of the predicate script must match the input owner.

**Comment by adlerjohn** [comment]
There are two ways to do this: simple hash or Merkle tree. Hash would be more like Bitcoin, but I imagine having a Merkle root of predicate code could be very useful for things like MAST and covenants. Of course, the latter will be a bit more expensive to compute. Leaning towards the latter for flexibility.
