### ISSUE TITLE
Restrict transaction witness malleability to only approved owners

### ISSUE THREAD

**Issue by rakita** [FuelLabs/fuel-specs#270]
Can we restrict tx that has possibility to be malleable, to only owners who we trust to do that.

John answer: It would require some fundamental changes to the transaction model to prevent third-party witness malleability in all cases, as it was designed to be malleated by third parties.

**Comment by rakita** [comment]
Lets bundle one more question toggether. 

What about BlockProducer paying for additional cost because, he is the one that has control over it

**Comment by Voxelot** [comment]
In the rollup mode, the block producer will always pay for relaying blocks to L1. Those costs will far outweigh the costs to peers for storing the extra witness data. 

In side-chain mode, this cost isn't currently captured at all. Perhaps we need some way to designate witnesses provided by the user vs added by third parties. That way if we wanted, we could implement schemes like deducting witness data created by the block producer from their coinbase award.
