### ISSUE TITLE
Specify how Fuel synchronizes with L1

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuel-specs#285]
## Leader Selection

Leader should be assigned for a slot: range of Ethereum blocks. (Maybe 10 minutes?) Happens entirely off-chain.
- `fuel-bft` should return leader given Fuel height, round, and validator set/voting power

1. If missed slot, increment round, and/or
2. If missed slot, next leader can submit missed block.

If there's a Commit, then don't re-org, instead submit later. If there's no Commit, then increment round.

## Batch submission

If validator set hasn't changed by >1/3, then can submit a range of block with only a single Commit. (Have to look up exact details. https://arxiv.org/abs/2010.07031)

## Deposits and valset updates

After some parameter (100 Ethereum blocks?) and Fuel block has Ethereum block number at least that, then deposit poofs into deposit set and can be spent.

## How to sync Ethereum block number (and timestamp) in header

Suggestion: contract checks timestamp and block number is (non-strictly) monotonic and within some tolerance (some parameter).

Tolerance (checked by contract **could just not check under honest majority assumption**):
1. Timestamp can't be in the future at all.
2. Ethereum block number can't be in the future at all.
3. Timestamp must be within [some parameter >0 number of slots] of current Ethereum time.
4. Ethereum block number must be within [some parameter >0 number of slots] of current Ethereum block number.

**Comment by simonr0204** [comment]
> If validator set hasn't changed by >1/3

I'm concerned about the gas cost of verifying this on ethereum.

**Comment by Voxelot** [comment]
Closing this for now, the approach has changed a lot since this was written.
