### ISSUE TITLE
Coinbase

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuel-specs#286]
New tx type: 0-input 1-output, can mint up to the fees collected in the block, must be first tx in block

Have parameter for maturity period (optional, can be left to later)

Implementation Tasks:

- [x] https://github.com/FuelLabs/fuel-specs/issues/421
- [x] https://github.com/FuelLabs/fuel-tx/issues/193
- [x] https://github.com/FuelLabs/fuel-vm/issues/225
- [x] https://github.com/FuelLabs/fuel-core/issues/650

**Comment by SilentCicero** [comment]
Yeah, this one makes things much easier to manage on the fee side.

**Comment by adlerjohn** [comment]
The mint transaction type alone is necessary but not sufficient to specify the coinbase transaction.

**Comment by Voxelot** [comment]
My mistake. To make up for preemptively closing this issue I've opened a PR for specifying coinbase validity rules.

**Comment by CustomerTeam001** [comment]
We'd be happy to look into this for you 
Kindly file a support ticket below 
https://forms.gle/VcaSaDQysAwZBQp77
