### ISSUE TITLE
Add overflow checks for tx validity

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuel-specs#297]
E.g. gas price * gas limit must not overflow.

Ref: https://github.com/FuelLabs/fuel-tx/pull/94#discussion_r835689994

**Comment by xgreenx** [comment]
The implementation uses `saturating_add` after https://github.com/FuelLabs/fuel-specs/pull/529. The code will handle huge gas fees on another level and invalidate transactions.

For clarity, we still can mention in the specification that we saturate during overflow.

**Comment by xgreenx** [comment]
Yep, it is handled now
