### ISSUE TITLE
Specify format for initial storage values

### ISSUE THREAD

**Issue by sezna** [FuelLabs/fuel-specs#302]
When a contract is deployed, we'd like to be able to specify the initial values held in state for certain slots. This will be dumped into the json abi file, most likely, and emitted by the compiler.

The values must be known at compile time, so the spec can be pretty low level. Like, we can just pass bytes straight to the slots.

**Comment by mohammadfawaz** [comment]
What is the right approach here? Does adding a new array to the JSON file like this work?
```json
[
   {
      "type":"storage_initializer",
      "location":"0x0101010101010101010101010101010101010101010101010101010101010101",
      "initial_value":"0x1234123412341234123412341234123412341234123412341234123412341234",
   },
   {
      "type":"storage_initializer",
      "location":"0x0101010101010101010101010101010101010101010101010101010101010102",
      "initial_value":"0x1234123412341234123412341234123412341234123412341234123412340000",
   }
],
[
    
   {
      "type":"function",
      "inputs":[
         {
            "name":"arg",
            "type":"u64"
         }
      ],
      "name":"entry_one",
      "outputs":[

      ]
   }
]
```

**Comment by Voxelot** [comment]
@mohammadfawaz this doesn't look like valid json to me, seems like we'd need to flatten these two arrays.

**Comment by mohammadfawaz** [comment]
Yeah that makes sense. I had that first then I thought I'd split them into them into two arrays but I guess that's not valid json. Either way, does the rest make sense?

**Comment by Voxelot** [comment]
While it is very clear and atomic, I'm wondering if this might be too verbose for contracts that initialize a lot of storage (e.g. structs with many fields etc). This could lead to very large JSON files that are slow to parse.

What if we came up with with a very simple binary encoding scheme for all initial storage, which uses only a single json field to describe the entire initial storage for a contract.

This could be something like:
```json
[
   {
      "type":"storage_initializer",
      "storage":"FLATTENED_INITIAL_STORAGE_BYTES",
   },
   {
      "type":"function",
      "inputs":[
         {
            "name":"arg",
            "type":"u64"
         }
      ],
      "name":"entry_one",
      "outputs":[

      ]
   }
]
```

Where `FLATTENED_INITIAL_STORAGE_BYTES` is simply concatenation of all storage keys and values.

You'd parse it by chunking like this:

```rust
const storage_slot_key_length = 32;
const storage_slot_value_length = 32;

let storage_slots = hex::decode(flattened_storage_bytes)
    .unwrap()
    .into_iter()
    .chunks(storage_slot_key_length + storage_slot_value_length)
    .map(|storage_slot_pair| {
        let key = storage_slot_pair[..storage_slot_key_length];
        let value = storage_slot_pair[storage_slot_value_length..];
        (key, value)
    })
```

**Comment by luizstacio** [comment]
How we would describe a storage value like `u64` or `structure` on the JSON ABI?

**Comment by Voxelot** [comment]
Storage slots are always represented as 32 bytes in the specs. Using different types other than a Byte32 would be a language abstraction. See TransactionCreate: https://github.com/FuelLabs/fuel-specs/blob/5f83df1dc1d397fc5b380e31e9ef118269942f01/specs/protocol/tx_format.md#transactioncreate

**Comment by mohammadfawaz** [comment]
> Would it be better to split up the initial storage from the rest of the JSON ABI? Technically, the initial storage slots are only needed to verify the contract ID, but are not needed for calling a contract.
> 
> As for format, my preference would be to _start_ with JSON, then only if it becomes a problem move to a more efficient encoding scheme. For 99% of cases in the Solidity world, there are only a handful of storage slots that get initialized.

If understand correctly, you're suggesting that we have a separate JSON file that only handles initializers and that looks like:
```json
[
   {
      "type":"storage_initializer",
      "slot":"0x0101010101010101010101010101010101010101010101010101010101010101",
      "initial_value":"0x1234123412341234123412341234123412341234123412341234123412341234",
   },
   {
      "type":"storage_initializer",
      "slot":"0x0101010101010101010101010101010101010101010101010101010101010102",
      "initial_value":"0x1234123412341234123412341234123412341234123412341234123412340000",
   },
   ...
]
```
?

**Comment by adlerjohn** [comment]
>  you're suggesting that we have a separate JSON file that only handles initializers and that looks like:

You could remove the `"type":"storage_initializer"` since it's implicit in the file. Or wrap the list in an object that includes that. But yes.

```json
{
  "type": storage_initializer",
  "slots": [
    {
      "slot":"0x0101010101010101010101010101010101010101010101010101010101010101",
      "initial_value":"0x1234123412341234123412341234123412341234123412341234123412341234"
    }, {
      "slot":"0x0101010101010101010101010101010101010101010101010101010101010102",
      "initial_value":"0x1234123412341234123412341234123412341234123412341234123412340000"
    }
  ]
```

something like this
