### ISSUE TITLE
Differentiate between `Address` and `ContractId` types

### ISSUE THREAD

**Issue by nfurfaro** [FuelLabs/fuel-specs#324]
In the EVM, both contracts and EOAs have an `address`, and can largely be treated the same.
In the FuelVM, an `Address` and a `ContractId` are not the same and are represented by 2 different types. It quickly becomes cumbersome to manually manage the 2 different types, and so a new type `Identity` was introduced to remove some of the friction. An `Identity` is an enum with 2 variants; `Address` & `ContractId`. The idea was that Identities could be passed around between functions and the developer could (for the most part) not care which variant it happened to be.

The problem with this approach is that in order to store an enum, we need 2 storage slots; 1 for the b256 inner value of an `Address` or a `ContractId` and a second for the `u64` tag. So, storing an `Identity` in storage will basically take up 2 storage slots, and two calls to srwq/swwq instead of 1.

We can of course simply store an `Address` or `ContractId` struct directly and not use the `Identity` type in storage, but then we have no way to know which type it is when reading from storage.
 
Both `Address` and `ContractId` types are structs with inner `b256` values. 
These `b256` values are indistinguishable from each other. However, if addresses and contract ids were made to be slightly different, we would always know which is which. This is the key to unlocking more efficient storage for these types.

One possibility was originally mentioned by @adlerjohn. What if we forced all contracts and addresses to start with a certain character? 
A few possibilities would be 
- to have the first bit unset for contracts and set for addresses. The existing bitwise operators could be used to query the first bit, and now you know which type this `b256` represents.
- Use a `0` or `1` in the hexadecimal literal to signify the type
- Use a `C` or `A` in the hexadecimal literal to signify the type

The largest concern would be to ensure that the resulting addresses are still suitable for safe use and there are no security compromises. Given that many other chains have prefixes for different types of addresses, it seems that this should be achievable. For example Bitcoin: 
>You can tell the difference between the types of addresses by if the address starts with a 1, 3, or bc1.

A fun visualization: https://www.royalfork.org/2014/08/11/graphical-address-generator/

**Comment by SilentCicero** [comment]
I'll add, as an option, instead of just a 0, 1 or C A, potentially we could consider a version byte.

For the byte data we have a 0-255.

These could represent network's in Fuel in addition to identifying EOA or Smart-contract.

For example: 0-127 could be EOA (with network ID's 0-127), then 128-255 for smart-contracts (with network ID's x - 128).

Although considering a single address / key could be and will likely be used for multiple networks. I don't know if the above is truly helpful. And we can pass id's over to name resolution systems like ENS instead of doing it this way.

**Comment by adlerjohn** [comment]
> Given that many other chains have prefixes for different types of addresses, it seems that this should be achievable. For example Bitcoin:

>    You can tell the difference between the types of addresses by if the address starts with a 1, 3, or bc1.

This is incorrect. The HRP of bech32 addresses aren't actually included on-chain, much like how the checksum upper/lowercase of Ethereum addresses aren't included on-chain. It's purely a user-facing encoding. The underlying thing the blockchain sees is the raw data.

**Comment by nfurfaro** [comment]
I stand corrected regarding the bitcoin addresses format. I guess what I wonder is:
Given a secure private key of sufficient randomness (256 bits of entropy?) we can derive a public key, which we then hash with sha256 to arrive at a 32-byte address. If we then force the single most significant bit to be a `0` or a `1`, do we weaken any security guarantees by doing this?

I can see that there would now be a chance that more than one public key could end up producing the same address, but I think there would be exactly 2 possible public keys from which the same address could be derived? That is, 2 public keys with all bits identical except for the first bit would both produce the same address, but what are the chances of 2 public keys with 255 identical bits?

**Comment by adlerjohn** [comment]
> do we weaken any security guarantees by doing this

Yes, we lose 1 bit of security. So, reducing from 256 to 255.

> a chance that more than one public key could end up producing the same address

That chance already exists actually! The proposed change would simple double the chance. From 1/115792089237316195423570985008687907853269984665640564039457584007913129639936 to 1/57896044618658097711785492504343953926634992332820282019728792003956564819968

**Comment by pixelcircuits** [comment]
Can't an EOAs `Address` be a predicate hash? How would we force a bit in that scenario without breaking the ability to verify the predicate script? Would we just accept it being off by one bit?

**Comment by adlerjohn** [comment]
> How would we force a bit in that scenario without breaking the ability to verify the predicate script?

There's two approaches here:

1. Post-process the hash by truncating off the leftmost bit for `Address`es and `ContractId`, making them different. This means when verifying any predicate hash you need to perform this post-processing.
2. Enforce as consensus rules that all `Address`es and `ContractId`s must start with either `0` or `1` bit. This means you might need to roll a few secret keys to get a pubkey that hashes to something that starts with a `0`, or change a contract salt to make it start with a `1`, or change a predicate's bytecode slightly to make it start with a `0`.

**Comment by adlerjohn** [comment]
> So, would EVM addresses fall under the post-processing approach, where the most significant 12 bytes are dropped after having the public key?

Yes, actually, post-processing is how Ethereum does addresses!

**Comment by pixelcircuits** [comment]
Would we have any issues with hardware wallets now? Were we supporting any fancy cryptography features (multisigs, multiparty computation, etc) that could break from this? Just trying to think of all the edge cases

**Comment by adlerjohn** [comment]
Don't think anything will break. It's really no different than how Ethereum does things.

**Comment by nfurfaro** [comment]
I'm commenting here to resurface this issue and see if we can possibly move forward with this?
Combined with #395 , this would really improve the usability, efficiency and safety of contract storage.

**Comment by adlerjohn** [comment]
I think we can avoid needing to do this by introducing an instruction to load/store sequential storage slots for much cheaper than doing it one-by-one.

**Comment by Voxelot** [comment]
Closing this as resolved for now since we currently support sequential slot loading, so this is likely sufficient for now. In the future we may also consider abandoning fixed 32 byte slots which avoids the need for sequential slot reading at all in the first place. Variable sized slots are now possible due to the transition to the hybrid zk-prover model.
