### ISSUE TITLE
Allow sub-unit gas prices

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuel-specs#342]
Rather than specifying gas prices in units of the base asset, specify them in some factor of units of the base asset, e.g. 1/1,000,000,000th of a unit. Then, when doing final gas accounting, round up to the nearest unit.

This will allow for much cheaper transactions, as otherwise even with a 1 unit gas price, transactions might still consume quite a bit of the base asset.

**Comment by vlopes11** [comment]
Recommended steps to implement:

- [ ] Implement the constant as consensus parameter in fuel-tx
- [ ] Perform the conversion  in transaction initialization/post-execution in fuel-vm
