### ISSUE TITLE
Bikeshed gas price factor

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuel-specs#347]
Transcluding from https://github.com/FuelLabs/fuel-specs/pull/343

Some considerations around parameter choice: a script that uses 10M gas can have a gas price of ~100B before you have to start worrying about overflow. Assuming ETH as the base asset:

1. With a factor of 1B, the maximum gas price is ~100 gwei. In the long run, this doesn't leave much room for a robust fee market.
2. With a factor of 1M, the maximum gas price is ~100,000 gwei. Lots of breathing room.
3. With a factor of 1,000, the minimum gas price is 0.001 gwei. This might not be cheap enough. Transactions may still cost on the order of cents even at the lowest gas price.

**Comment by xgreenx** [comment]
The consensus parameters has `gas_price_factor` to allow that behavior.
