### ISSUE TITLE
Typo in Output Message ID

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuel-specs#360]
# Summary

Description uses the term "input" instead of "output".

https://github.com/FuelLabs/fuel-specs/blob/304ad7f331c8f90a4697f6897190361dc32d492f/specs/protocol/identifiers.md?plain=1#L43

# Screenshot
![1](https://user-images.githubusercontent.com/103777923/174883194-1e544da0-a772-4d0c-992b-eba342300c2f.png)

**Comment by adlerjohn** [comment]
FYI @Braqzen you can click on "Display the source blob" to get source code for markdown files, after which you can link to exact lines.

https://github.com/FuelLabs/fuel-specs/blob/304ad7f331c8f90a4697f6897190361dc32d492f/specs/protocol/identifiers.md?plain=1#L43

![blob](https://user-images.githubusercontent.com/3290375/174883855-3a5fe2af-8647-4ed1-bc84-85b6922b8fe2.png)
