### ISSUE TITLE
Follow-up on `GTF`

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuel-specs#369]
Should we leave more spacing between script tx fields and create tx fields? I noticed you left plenty of space between the input, output and witness values, but script tx doesn't have much room to grow.

Also is there a way we could assign these imm values to make compatibility checking more efficient using bitmasks?

I.e. if script tx fields fit within a bitmask of `0x00ff` and create tx fields fit within a bitmask of `0xff00`, then it should be easier to specify which fields are not available. 

Right now this seems a little fuzzy by just saying:

> Panic If:
> The input or output type does not match (`OutputChange` and `OutputVariable` count as `OutputCoin`)

We should be able to specify exactly what is valid or invalid.

_Originally posted by @Voxelot in https://github.com/FuelLabs/fuel-specs/pull/353#discussion_r902163647_

**Comment by xgreenx** [comment]
Done during https://github.com/FuelLabs/fuel-specs/pull/514
