### ISSUE TITLE
Add chain ID instruction

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuel-specs#374]
Follow-on on #340

**Comment by Voxelot** [comment]
Should this be an arg to GTF instead, since the chain id would be part of the tx format?

**Comment by adlerjohn** [comment]
Good idea!

**Comment by Voxelot** [comment]
Since we decided to make chain_id implicitly encoded into the tx id without needing to take up space on each txn, this has been added to the GM opcode instead.

https://github.com/FuelLabs/fuel-specs/blob/master/src/fuel-vm/instruction-set.md#gm-get-metadata
