### ISSUE TITLE
Generate type and type IDs for event logging in a JSON file

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/fuel-specs#375]
In a separate JSON file called `*-types.json`, we can emit all the types used by a contract and assign them IDs. This is useful for event logging where the `log<T>()` call in the Sway standard library can be modified to include an intrinsic that would help point to the right type that's being logged so that the SDK can pick that up from the JSON file and interpret the data being logged and display it properly.

Adding the ABI label though this is not strictly related to the ABI. Just couldn't find a better label for now.

**Comment by adlerjohn** [comment]
Note that Solidity uses a 4-byte selector for "custom errors" and I think structs that are logged. We could do that, or have simple numeric IDs.
