### ISSUE TITLE
Behavior of logarithm when less than base

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuel-specs#380]
When less than base, the log of a number is negative. Since we don't have negative numbers in the VM, need to specify this case.

Noted by @rostyslavtyshko

**Comment by Dentosal** [comment]
Logarithm two positive integers is never negative. See https://www.wolframalpha.com/input?i=solve+log%28x%2Cy%29+%3C+0+where+x%3E%3D1%2C+y%3E%3D1. If base is zero, no solutions exist. If the argument is zero, the solution is negative infinity for any positive integer base.

To summarize, the output is never negative for us.
