### ISSUE TITLE
Consider hosting the spec as an mdbook?

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuel-specs#387]
Perhaps it's worth considering hosting the spec under an mdbook?

Some benefits that come to mind:

- Easier to navigate for folk unfamiliar with GitHub.
- The chapter column provides a nice overview with subheaders etc.
- Left and right keys for navigating through pages.
- Supports simpler, real-time search.
- Has a community providing external tooling for conversion to PDF, ePub, etc, handy for offline or mobile reading.

For the most part the file layout would almost be the same and folk would still be welcome to peruse by clicking through GitHub links if they prefer.

I remember there being some brief discussion around keeping this as raw GitHub markdown but I don't recall the reasoning :thinking:

**Comment by adlerjohn** [comment]
No, there wasn't any requirement on raw markdown. Just a requirement to keep the barrier to entry low, which mdbook still satisfies. The only reason it hasn't been done yet is because I have no time 😂😭

**Comment by vnepveu** [comment]
Would love to have the specs as an MDbook!
