### ISSUE TITLE
Consider adding `GTF_OUTPUT_VARIABLE_AMOUNT` and `GTF_OUTPUT_CHANGE_AMOUNT` fields to `gtf`

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/fuel-specs#402]
Consider adding `GTF_OUTPUT_VARIABLE_AMOUNT` and `GTF_OUTPUT_CHANGE_AMOUNT` fields to `gtf`. A field for `OutputChange` may be redundant because the value is always 0, but it's worth considering adding it just for completeness.

**Comment by Voxelot** [comment]
cc @vlopes11

**Comment by pixelcircuits** [comment]
It could also be helpful to include an `_AMOUNT`, `_ASSET_ID` and `_TO` for `OutputChange` and `OutputVariable` for completeness. The bridge predicate already has a use case to check for `GTF_OUTPUT_CHANGE_ASSET_ID`

**Comment by Voxelot** [comment]
Given change amounts are only set post-execution, I'm not sure if there's a real use case for `GTF_OUTPUT_CHANGE_AMOUNT`.

**Comment by xgreenx** [comment]
I think it is better not to support useless `GTF`, because it only increases the codebase burden and adds confusion to the user, which expects an actual value.

If we still want to do that, then we can reopen this issue and continue discussion again
