### ISSUE TITLE
Should predicates allow backward jumps if a gas limit is imposed?

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/fuel-specs#413]
Predicates do not currently allow backward jumps. This is a protocol restriction:

> During predicate mode, hitting any of the following instructions causes predicate verification to halt, returning Boolean false:
>
>  1. Any contract instruction.
>  2. JI, JNEI, JMP or JNE with jump-to value less than or equal to $pc (these would allow loops). In other words, $pc must be strictly increasing.

The downside of the above is that function calls cannot be properly supported because they require jumps _to_ and _from_ the functions being called, which evidently leads to having backward jumps at some point. For now, the compiler will inline all function calls in predicates but that can lead to bytecode size bloat.

@adlerjohn mentioned that it may be possible to remove the restriction above if we impose a gas limit that guarantees that the predicate eventually halts execution.

**Comment by adlerjohn** [comment]
If predicates have a guaranteed upper bound on cost (e.g. by using gas metering), then sure. One thing we have to be careful of is that changes to the gas schedule will require re-verifying predicates in the mempool, along with the possibility that some predicates may become unsatisfiable.

**Comment by mohammadfawaz** [comment]
@mitch-fuel assigning this to you as it's related to #440

**Comment by Voxelot** [comment]
Closing as this issue is resolved and backward jumps are allowed.
