### ISSUE TITLE
What is the meaning of the receiptsRoot in TransactionScript?

### ISSUE THREAD

**Issue by felicityin** [FuelLabs/fuel-specs#420]
What is the meaning of the receiptsRoot in TransactionScript: https://github.com/FuelLabs/fuel-specs/blob/master/specs/protocol/tx_format.md#transactionscript

**Comment by Voxelot** [comment]
This should probably be moved to discord dev chat or github discussions, as it's not a bug or feature request.

https://github.com/FuelLabs/fuel-specs/discussions

**Comment by felicityin** [comment]
> This should probably be moved to discord dev chat or github discussions, as it's not a bug report or a feature request.
> 
> https://github.com/FuelLabs/fuel-specs/discussions

OK
