### ISSUE TITLE
Unique identifier of the `Mint` transaction

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-specs#421]
`Mint` transaction generates outputs requiring a unique `UtxoId` or `CoinId`(because outputs are `Coins`) to be spendable. 

Take into account the conditions to create a `Mint` transaction unique(it can be created only by the block producer), we can make the transaction unique by adding block height + index in the block. Hash from those two fields produces the `TxId` that can be used in the `Coin`s.

Does it cover all cases, or do we need to think about something more?

**Comment by Voxelot** [comment]
Seems like it should be sufficient, although I wonder if the hash should also commit to the outputs of the mint? cc @adlerjohn

**Comment by adlerjohn** [comment]
To clarify, the hash of the block height + transaction index is sufficient to uniquely identify the transaction, i.e. get a transaction ID. The outpoint (transaction ID + output index) could be used to uniquely identify a coin output from a mint transaction.

It would be nice if the ID also committed to the actual transaction instead of just the transaction's location (makes various things like fraud proofs easier, and prevents some corner cases with re-orgs). As such, I'll propose:

```
hash(block height ++ transaction index ++ hash(serialized transaction))
```

as the transaction ID for a mint transaction.

As an aside, at some point these hash identifiers should be domain-separated for security (#201), but that can be left for future work.

**Comment by xgreenx** [comment]
I want to clarify what is "hash(serialized transaction)" is here?=) It could be: 
1. Hash of canonically serialized transaction with 64 bits alignment and `Mint` identifier at the beginning. 
1. Hash of some other serialization
1. Hash from each inner field: `block_height`, `index`, and `outputs`. 

Also, for the history: `Output`s should be prepared before serialization/hashing as it is done for `Script` and `Create` transactions.

**Comment by xgreenx** [comment]
And another question, do we want to use the `Output` type, or are we okay to use directly `Output::Coin` and remove this validation rule "Any output is not of type OutputType.Coin"?

**Comment by adlerjohn** [comment]
https://github.com/FuelLabs/fuel-tx/pull/202/files#r1004962913

Actually, if we insert the block height and transaction index into the Mint transaction itself then a special rule for the transaction ID isn't needed.

**Comment by xgreenx** [comment]
Cool, we agreed on it. I will create PR with an updated version=)

**Comment by Voxelot** [comment]
> I want to clarify what is "hash(serialized transaction)" is here?=) It could be:
> 
> 1. Hash of canonically serialized transaction with 64 bits alignment and `Mint` identifier at the beginning.
> 2. Hash of some other serialization
> 3. Hash from each inner field: `block_height`, `index`, and `outputs`.
> 
> I think it is variant 1, but I want to be sure=)
> 
> And do we really want to do double hashing? Hash of the serialized transaction already includes `block_height` and `tx_index`. It will look like `hash(block height ++ transaction index ++ hash(serialize(block height ++ transaction index ++ outputs)))`

Not sure what you mean by double hashing, as the tx id for script or create doesn't depend on block height ++ tx idx. I think option 1 makes sense and is the most consistent with how other txs work.

**Comment by Voxelot** [comment]
Clarified with @xgreenx that the double hashing was related to having a special rule for computing the mint tx id which is no longer applicable due to https://github.com/FuelLabs/fuel-specs/pull/423
