### ISSUE TITLE
Gas Metered Predicates

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-specs#440]
Make predicates use gas metering to constrain execution.

By moving to gas-metered predicates we could:

- Perform backwards jumps, allowing the compiler to simplify how it compiles predicates: https://github.com/FuelLabs/fuel-specs/issues/413
- Load code from state, avoiding tx bloat: https://github.com/FuelLabs/fuel-specs/issues/119
- Accurately constrain predicate verification time. For example, `ECR` is several orders of magnitude more costly than most other opcodes. With byte metering, we'd charge the same for a predicate that only does simple ALU ops as a one that performs ECR's, even they would have drastically different evaluation costs.

Some risks to consider:

- Transactions may no longer be statelessly verifiable if LDC was supported, possibly requiring them to be re-evaluated periodically
- The gas limit should be more restrictive compared to scripts, otherwise nodes could get spammed with expensive predicates without being able to charge any fees if they're invalid.

**Comment by Voxelot** [comment]
> Should we charge for running predicates? How would this be done?
We'd need a way to track how much gas / fees were consumed by the predicates and deduct that from the total gas limit before script execution. They should be chargeable by the block producer just like any other cost such as metered bytes or regular gas used in scripts.

> Predicates are typically executed multiple times, should the gas be more expensive in predicates?

When validating transactions prior to execution (i.e. txpool or block sync), the predicates could be verified a single time and don't need to be checked again during block execution. This is mainly an implementation detail that would involve changing the block executor to accept either checked or unchecked transactions to avoid rechecking. With some optimizations we could ensure that each transaction is checked once.

> Should we have different gas costs for predicates, e.g. making slow instructions even more costly than in contracts?

From the perspective of doing this since they may be executed multiple times, I think this is a solvable problem in the VM/Node implementation to avoid re-execution. 

The main risk with predicates imo is eager evaluation, and if the check fails for any reason there's no way to claim a fee unlike scripts making DOS easier. However, I don't think raising prices really mitigates that concern and it's also a problem that still exists in the current execution model. Since there are many ways to DOS/spam txpools besides predicates, I think this would largely need to be mitigated via things like peer reputation + traditional API management approaches such as rate-limiting at the load balancer.

> Is it actually practical or sensible to support LDC instraction? How does losing stateless verification affect us? Is it even worth having predicates anymore, if they cannot be verified statelessly?

I agree that this complicates the model a lot, and is why we should defer code loading as a separate potential feature. It should theoretically be possible and may not be as bad as it seems, while also allowing for significant reduction in predicate sizes if things like the sway std lib could be dynamically linked in.

> If we decide to allow LDC, then we could likely support CCP, CROO, CSIZ as well. Maybe storage reads could be supported as well?

The difference between LDC and other kinds of arbitrary state access, is that contract code is immutable state whereas other arbitrary storage is mutable and would require the predicates to be continuously rechecked for validity. The immutability of contract code is the main reason why it may not be as bad as it seems. However, I think some additional work is needed around defining whether these are actually contracts that require a `call` or just libraries, and whether that also requires specifying read-only contract inputs or some other kind of access list etc.

**Comment by adlerjohn** [comment]
LDC isn't _stateless_ however it is _monotonic_. Therefore it wouldn't require re-evaluation of predicates.
