### ISSUE TITLE
ABI type names should be call paths instead of just strings

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/fuel-specs#449]
E.g. 
```rust
abi MyContract {
    fn test_function(a: lib1::Foo, b: lib2::Foo) -> bool;
}
```
To avoid ambiguity, the two `Foo`s need to be differentiated somehow and the only way to do so is by including their paths from the package root in the JSON ABI.

**Comment by adlerjohn** [comment]
Dup of #450?

**Comment by mohammadfawaz** [comment]
Yes. Looks like I created this one and transferred #450 from Sway 🤔 . Will close this one.
