### ISSUE TITLE
LDC support in predicate feature

### ISSUE THREAD

**Issue by Marvin8122** [FuelLabs/fuel-specs#456]
# LDC support

Is it actually practical or sensible to support LDC instraction? How does losing stateless verification affect us? Is it even worth having predicates anymore, if they cannot be verified statelessly?

If we decide to allow LDC, then we could likely support CCP, CROO, CSIZ as well. Maybe storage reads could be supported as well?

_Originally posted by @Dentosal in https://github.com/FuelLabs/fuel-specs/issues/440#issuecomment-1378497483_

**Comment by SilentCicero** [comment]
Related: https://github.com/FuelLabs/fuel-specs/pull/492
