### ISSUE TITLE
Update Panic Receipt

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuel-specs#475]
The specs document the panic with a `reason` as a string; however, it seems to use an `InstructionResult` struct instead. The documentation should be updated to reflect this.

E.g.

```rust
Panic { id: 522e813b7c17eb399aaca0a3ee7293d7a93191b0a40e7baec97d1b5e0f1637dd, reason: InstructionResult { reason: ArithmeticOverflow, instruction: 759243985 }, pc: 12788, is: 11624, contract_id: None }
```

**Comment by Voxelot** [comment]
This is just the internal representation we use within the VM, while the specs only mention how they should be json serialized. Since this is a view of rust debug formatting and not json serialization, this isn't breaking the spec.
