### ISSUE TITLE
Big integer arithmetic

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-specs#478]
FuelVM currently only support u64 based arithmetic. This is insufficient for most DEX usecases, which necessitates using sway libraries for larger integers. The problem with this approach is that due to in-lining and just the overall bulk associated with supporting operations like u256 division using only u64s, the contract sizes for even relatively simple contracts is growing very large. 

This can be partially solved through usage of LDC, however it also adds a lot of VM overhead if we can't take advantage of natively supported machine instructions for big int math. Since the EVM supports u256 by default, the fraud proof overhead of adding wide number arithmetic instructions should be minimal.

Research whether u128 opcodes would be sufficient to cut down most of the bytecode overhead, and which operations would be the most frequently used. E.g. A special `u128::mul_div` may increase performance a lot for DEX applications compared to using separate mul and div opcodes.

**Comment by Dentosal** [comment]
See https://github.com/FuelLabs/fuel-core/issues/1117 for some initial discussion

**Comment by Dentosal** [comment]
Done in https://github.com/FuelLabs/fuel-specs/pull/483
