### ISSUE TITLE
`ecr` opcode is no longer supported

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuel-specs#512]
In the instruction set, under [cryptographic instructions](https://specs.fuel.network/master/fuel-vm/instruction-set.html#cryptographic-instructions), the `ecr` opcode is mentioned 3 times (unsure if bug or if the opcode performs all 3 functions).

With the recent bump of the client it appears that `forc` also has deprecated the opcode in favour of `eck1`.
The documentation is out of date.

**Comment by SilentCicero** [comment]
Mind making a PR to fix. Good catch.

**Comment by Braqzen** [comment]
> Mind making a PR to fix. Good catch.

I can do but I have not done so because I do not know if all 3 are meant to be replaced with `eck1`.
