### ISSUE TITLE
Update specs fee calculation to include custom gas price

### ISSUE THREAD

**Issue by MitchTurner** [FuelLabs/fuel-specs#544]
Need to include the changes that were made here:
https://github.com/FuelLabs/fuel-vm/pull/672

This should include the calculation of the fee using a base gas price, the addition of the `Tip` policy, as well as the changes made to the `Mint` transaction.

**Comment by xgreenx** [comment]
Done in the https://github.com/FuelLabs/fuel-specs/pull/546
