### ISSUE TITLE
Document error

### ISSUE THREAD

**Issue by caketang** [FuelLabs/fuel-specs#550]
[TypeScript  getting-started](https://docs.fuel.network/docs/fuels-ts/getting-started/),    when click the pnpm and npm button,   the pnpm button  shows  'npm install fuels --save',  and the npm  button shows 'pnpm add fuels'.  

correct expectations:

when click pnpm button that should show 'pnpm add fuels'

when click npm button that should show 'npm install fuels --save'

**Comment by xgreenx** [comment]
It is a wrong repository for this issue, please open the issue in the documentation repository instead
