### ISSUE TITLE
Beta 5/bridge

### ISSUE THREAD

**Issue by Genny1999** [FuelLabs/fuel-specs#551]
I noticed that the beta 5 bridge suddenly stops detecting my fuel wallet mid transactions (wallet not detected), will have to refresh like twice to continue my  transaction. Might be a bug or something because it worked fine yesterday.

**Comment by altayi** [comment]
ok

**Comment by xgreenx** [comment]
Thank you for reporting the issue. This repository is not related to the bridge. Could you post it to the forum or https://github.com/FuelLabs/fuel-bridge instead, please?
