### ISSUE TITLE
Ecosystem

### ISSUE THREAD

**Issue by gouravghosh02** [FuelLabs/fuel-specs#557]
When ecosystem work complete and testnet available![Screenshot_2024-03-11-16-45-52-314_site.mises.browser.jpg](https://github.com/FuelLabs/fuel-specs/assets/88235006/15245778-2d93-4862-87b6-6dc80adead4f)

![Screenshot_2024-03-11-16-44-25-711_site.mises.browser.jpg](https://github.com/FuelLabs/fuel-specs/assets/88235006/7c141039-0c05-425b-8b6c-fdbae0a9ad2e)

**Comment by xgreenx** [comment]
Thank you for the issue. It is not clear how it reloads to the specification, so I will code it for now until further details are available.
