### ISSUE TITLE
Add GM getter for the base asset id

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-specs#559]

**Comment by Dentosal** [comment]
@xgreenx GM is a bit weird opcode for this, as it currently returns either Word-sized value or a pointer to memory. In this case there seems to be no requirement for the base asset id to exist in memory, so there's nowhere to point to. Or maybe it's always part of runtime balances and we could point to the value in that array?

**Comment by Dentosal** [comment]
As discussed, the way to do this is adding the base asset id to memory on VM startup.
