### ISSUE TITLE
Blob tx and loading

### ISSUE THREAD

**Issue by Dentosal** [FuelLabs/fuel-specs#589]
Tracking issue for `Blob` transactions and related opcodes.

As discussed with the client team on 2024-06-20, to allow contracts larger than the contract size limit, and to allow upgradability, we'll be adding a new tx type that's just a bunch of bytes, and opcodes to load subsections of that. The whole thing reminds contracts and `LDC` a bit, but blob won't have state or balances, and the corresponding load instructions will be slightly different.

Implemented in:
- https://github.com/FuelLabs/fuel-specs/pull/592
- https://github.com/FuelLabs/fuel-vm/pull/780
- https://github.com/FuelLabs/fuel-core/pull/1988

**Comment by xgreenx** [comment]
All sub-tasks are done=)
