### ISSUE TITLE
improved the code

### ISSUE THREAD

**Issue by olegmosso** [FuelLabs/fuel-specs#608]
expected_root:
  encoding: hex
  value: e912e97abc67707b2e6027338292943b53d01a7fbd7b244674128c7e468dd696
name: Test Delete Sparse Union
steps:
  # First, perform all update actions before deletes to avoid removing keys being updated.
  - action: update
    data:
      encoding: utf-8
      value: DATA
    key:
      encoding: hex
      value: df3f619804a92fdb4057192dc43dd748ea778adc52bc498ce80524c014b81119
  - action: update
    data:
      encoding: utf-8
      value: DATA
    key:
      encoding: hex
      value: b40711a88c7039756fb8a73827eabe2c0fe5a0346ca7e0a104adc0fc764f528d
  - action: update
    data:
      encoding: utf-8
      value: DATA
    key:
      encoding: hex
      value: 433ebf5bc03dffa38536673207a21281612cef5faa9bc7a4d5b9be2fdb12cf1a
  - action: update
    data:
      encoding: utf-8
      value: DATA
    key:
      encoding: hex
      value: 88185d128d9922e0e6bcd32b07b6c7f20f27968eab447a1d8d1cdf250f79f7d3
  - action: update
    data:
      encoding: utf-8
      value: DATA
    key:
      encoding: hex
      value: 1bc5d0e3df0ea12c4d0078668d14924f95106bbe173e196de50fe13a900b0937
  - action: update
    data:
      encoding: utf-8
      value: DATA
    key:
      encoding: hex
      value: 221f8af2372a95064f2ef7d7712216a9ab46e7ef98482fd237e106f83eaa7569
  - action: update
    data:
      encoding: utf-8
      value: DATA
    key:
      encoding: hex
      value: b253668f6b59f1ff28522831931e4d3c5a3de533965af22e961735437c0172cb
  - action: update
    data:
      encoding: utf-8
      value: DATA
    key:
      encoding: hex
      value: 1561ade0621c5acf44b780521f95a1e0b19b4e5032945b860c4032fc28a3a23b
  - action: update
    data:
      encoding: utf-8
      value: DATA
    key:
      encoding: hex
      value: 17eb70034b5b71092521d184c5e7b069d47de657e51aef2be11a00c115036943
  - action: update
    data:
      encoding: utf-8
      value: DATA
    key:
      encoding: hex
      value: 3b28a6c3766c6295adad976d349705ef49393fbfdebe4facb5862d2cdfa285d3

  # Now perform the delete actions. Ensure none of the deleted keys are updated first.
  - action: delete
    key:
      encoding: hex
      value: b40711a88c7039756fb8a73827eabe2c0fe5a0346ca7e0a104adc0fc764f528

**Comment by xgreenx** [comment]
Thank you for creating the issue. It is not clear what is the purpose of the issue, so I will close it for now until future information
